ALTER TABLE sessions ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE sessions ADD COLUMN auto_titled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE messages ADD COLUMN favorite INTEGER NOT NULL DEFAULT 0;
